export const INITIAL_ASSETS = [
  // TI (Carlos Silva)
  {
    id: 'pat-1001',
    numeroPatrimonio: 'PAT-1001',
    descricao: 'Notebook Dell Latitude 5430 Core i7 16GB 512GB SSD',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-ti',
    setorNome: 'Tecnologia da Informação (TI)',
    localizacao: 'Bloco A - Sala 101 - Mesa 03',
    responsavel: 'Carlos Silva',
    anoAquisicao: 2023,
    valorOriginal: 6200.00,
    valorAtual: 4650.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [
      { data: '2023-03-10 09:30', acao: 'Cadastro Inicial', usuario: 'Administrador' }
    ]
  },
  {
    id: 'pat-1002',
    numeroPatrimonio: 'PAT-1002',
    descricao: 'Servidor Rack Dell PowerEdge R640 64GB 4TB SAS',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-ti',
    setorNome: 'Tecnologia da Informação (TI)',
    localizacao: 'Bloco A - Data Center - Rack 02',
    responsavel: 'Carlos Silva',
    anoAquisicao: 2022,
    valorOriginal: 28500.00,
    valorAtual: 19950.00,
    status: 'CONFERIDO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=500&auto=format&fit=crop&q=60',
    conferidoEm: '2026-09-30 14:15',
    conferidoPor: 'Carlos Silva (TI)',
    cautelaAtual: null,
    historico: [
      { data: '2022-06-15 10:00', acao: 'Cadastro Inicial', usuario: 'Administrador' },
      { data: '2026-09-30 14:15', acao: 'Conferência de Carga', usuario: 'Carlos Silva (TI)' }
    ]
  },
  {
    id: 'pat-1003',
    numeroPatrimonio: 'PAT-1003',
    descricao: 'Switch Cisco Catalyst 48 Portas Gigabit PoE+',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-ti',
    setorNome: 'Tecnologia da Informação (TI)',
    localizacao: 'Bloco A - Data Center - Rack 01',
    responsavel: 'Carlos Silva',
    anoAquisicao: 2021,
    valorOriginal: 12400.00,
    valorAtual: 6200.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: []
  },
  {
    id: 'pat-1004',
    numeroPatrimonio: 'PAT-1004',
    descricao: 'Projetor Epson PowerLite W49 3800 Lumens WXGA',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-ti',
    setorNome: 'Tecnologia da Informação (TI)',
    localizacao: 'Bloco A - Sala 101 - Armário Suporte',
    responsavel: 'Carlos Silva',
    anoAquisicao: 2023,
    valorOriginal: 4100.00,
    valorAtual: 3280.00,
    status: 'EM_CAUTELA',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: {
      id: 'caut-501',
      responsavelRetirada: 'Lucas Rocha (Marketing)',
      documento: 'MG-14.882.102',
      telefone: '(11) 98765-4321',
      setorDestino: 'Marketing & Comunicação',
      dataRetirada: '2026-09-28 09:00',
      dataPrevistaDevolucao: '2026-10-02 18:00',
      finalidade: 'Apresentação do Plano Anual de Comunicação na Sala Multiuso',
      status: 'EM_ANDAMENTO'
    },
    historico: [
      { data: '2026-09-28 09:00', acao: 'Cautela emitida para Lucas Rocha (Marketing)', usuario: 'Carlos Silva' }
    ]
  },

  // Administrativo (Mariana Souza)
  {
    id: 'pat-2001',
    numeroPatrimonio: 'PAT-2001',
    descricao: 'Impressora Multifuncional Laser Colorida HP LaserJet Pro MFP 4303fdw',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-adm',
    setorNome: 'Administrativo',
    localizacao: 'Bloco A - Sala 102 - Área de Impressão',
    responsavel: 'Mariana Souza',
    anoAquisicao: 2023,
    valorOriginal: 3950.00,
    valorAtual: 3160.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: []
  },
  {
    id: 'pat-2002',
    numeroPatrimonio: 'PAT-2002',
    descricao: 'Mesa de Reunião Oval 10 Lugares em Madeira Nobre com Calhas Elétricas',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-adm',
    setorNome: 'Administrativo',
    localizacao: 'Bloco A - Sala 102 - Sala de Reunião A',
    responsavel: 'Mariana Souza',
    anoAquisicao: 2020,
    valorOriginal: 7800.00,
    valorAtual: 3900.00,
    status: 'CONFERIDO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=500&auto=format&fit=crop&q=60',
    conferidoEm: '2026-09-30 11:20',
    conferidoPor: 'Mariana Souza (Administrativo)',
    cautelaAtual: null,
    historico: []
  },
  {
    id: 'pat-2003',
    numeroPatrimonio: 'PAT-2003',
    descricao: 'Aparelho de Ar Condicionado Split Inverter 24000 BTUs Daikin',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-adm',
    setorNome: 'Administrativo',
    localizacao: 'Bloco A - Sala 102 - Parede Norte',
    responsavel: 'Mariana Souza',
    anoAquisicao: 2022,
    valorOriginal: 5200.00,
    valorAtual: 3640.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: []
  },

  // Financeiro / Contabilidade (Roberto Mendes)
  {
    id: 'pat-3001',
    numeroPatrimonio: 'PAT-3001',
    descricao: 'Cofre Mecânico e Digital Blindado Guarda Valores 120kg',
    categoria: 'Outros Bens Permanentes',
    setorId: 'sec-fin',
    setorNome: 'Financeiro / Contabilidade',
    localizacao: 'Bloco A - Sala 103 - Sala Reservada Tesouraria',
    responsavel: 'Roberto Mendes',
    anoAquisicao: 2019,
    valorOriginal: 8900.00,
    valorAtual: 5340.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: []
  },
  {
    id: 'pat-3002',
    numeroPatrimonio: 'PAT-3002',
    descricao: 'Fragmentadora de Papel e Cartões de Alta Segurança Corte em Partículas',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-fin',
    setorNome: 'Financeiro / Contabilidade',
    localizacao: 'Bloco A - Sala 103 - Apoio Fiscal',
    responsavel: 'Roberto Mendes',
    anoAquisicao: 2021,
    valorOriginal: 2450.00,
    valorAtual: 1225.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: []
  },

  // RH (Fernanda Lima)
  {
    id: 'pat-4001',
    numeroPatrimonio: 'PAT-4001',
    descricao: 'Relógio de Ponto Eletrônico Biométrico e Facial Homologado Portaria 671',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-rh',
    setorNome: 'Recursos Humanos (RH)',
    localizacao: 'Bloco A - Hall de Entrada Principal',
    responsavel: 'Fernanda Lima',
    anoAquisicao: 2023,
    valorOriginal: 3100.00,
    valorAtual: 2480.00,
    status: 'CONFERIDO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=500&auto=format&fit=crop&q=60',
    conferidoEm: '2026-09-30 08:45',
    conferidoPor: 'Fernanda Lima (RH)',
    cautelaAtual: null,
    historico: []
  },

  // Almoxarifado Central (João Pereira)
  {
    id: 'pat-5001',
    numeroPatrimonio: 'PAT-5001',
    descricao: 'Empilhadeira Manual Hidráulica Capacidade 2.500kg Rodas Duplas',
    categoria: 'Ferramentas e Máquinas',
    setorId: 'sec-almox',
    setorNome: 'Almoxarifado Central',
    localizacao: 'Galpão 01 - Corredor Central',
    responsavel: 'João Pereira',
    anoAquisicao: 2022,
    valorOriginal: 4800.00,
    valorAtual: 3360.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: []
  },
  {
    id: 'pat-5002',
    numeroPatrimonio: 'PAT-5002',
    descricao: 'Coletor de Dados Zebra TC21 Android Touch Barcode 2D',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-almox',
    setorNome: 'Almoxarifado Central',
    localizacao: 'Galpão 01 - Estação de Expedição',
    responsavel: 'João Pereira',
    anoAquisicao: 2024,
    valorOriginal: 3750.00,
    valorAtual: 3375.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1526738549149-8e07eca6c147?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: []
  },
  {
    id: 'pat-5003',
    numeroPatrimonio: 'PAT-5003',
    descricao: 'Balança Eletrônica Plataforma Industrial 500kg Inox',
    categoria: 'Instrumentos e Medição',
    setorId: 'sec-almox',
    setorNome: 'Almoxarifado Central',
    localizacao: 'Galpão 01 - Baia de Recebimento',
    responsavel: 'João Pereira',
    anoAquisicao: 2021,
    valorOriginal: 3200.00,
    valorAtual: 1920.00,
    status: 'BAIXADO',
    baixado: true,
    dadosBaixa: {
      data: '2026-08-14 16:30',
      motivo: 'Quebra / Inservível com custo de reparo superior a 80% do valor',
      observacoes: 'Célula de carga danificada irreversivelmente após sobrecarga de empilhadeira externa. Laudo técnico anexo e aprovado pela diretoria para descarte sustentável.',
      anexos: [
        { nome: 'Laudo_Tecnico_Balanca_5003.pdf', tipo: 'application/pdf', tamanho: '1.4 MB' },
        { nome: 'Termo_Baixa_Patrimonial_Assinado.pdf', tipo: 'application/pdf', tamanho: '850 KB' }
      ]
    },
    foto: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [
      { data: '2026-08-14 16:30', acao: 'Baixa Patrimonial Aprovada', usuario: 'João Pereira (Almoxarifado)' }
    ]
  },

  // Operações e Logística (André Santos)
  {
    id: 'pat-6001',
    numeroPatrimonio: 'PAT-6001',
    descricao: 'Veículo Utilitário Fiorino Endurance 1.4 Flex Branca',
    categoria: 'Veículos e Transporte',
    setorId: 'sec-op',
    setorNome: 'Operações e Logística',
    localizacao: 'Estacionamento Operacional - Vaga 12',
    responsavel: 'André Santos',
    anoAquisicao: 2023,
    valorOriginal: 94000.00,
    valorAtual: 81500.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: []
  },

  // Jurídico (Beatriz Ramos)
  {
    id: 'pat-7001',
    numeroPatrimonio: 'PAT-7001',
    descricao: 'Arquivo Deslizante de Aço com Chave Especial 8 Módulos',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-jur',
    setorNome: 'Jurídico & Compliance',
    localizacao: 'Bloco B - Sala 201 - Arquivo Morto Jurídico',
    responsavel: 'Dra. Beatriz Ramos',
    anoAquisicao: 2020,
    valorOriginal: 16500.00,
    valorAtual: 9900.00,
    status: 'CONFERIDO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=500&auto=format&fit=crop&q=60',
    conferidoEm: '2026-09-30 16:00',
    conferidoPor: 'Dra. Beatriz Ramos (Jurídico)',
    cautelaAtual: null,
    historico: []
  },

  // Marketing (Lucas Rocha)
  {
    id: 'pat-8001',
    numeroPatrimonio: 'PAT-8001',
    descricao: 'Câmera Mirrorless Sony Alpha A7 IV com Lente 24-70mm f/2.8 GM',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-mkt',
    setorNome: 'Marketing & Comunicação',
    localizacao: 'Bloco B - Sala 202 - Estúdio de Gravação',
    responsavel: 'Lucas Rocha',
    anoAquisicao: 2024,
    valorOriginal: 24900.00,
    valorAtual: 22410.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: []
  },

  // Engenharia (Paulo Vieira)
  {
    id: 'pat-9001',
    numeroPatrimonio: 'PAT-9001',
    descricao: 'Gerador a Diesel Silenciado Trifásico 150kVA Cummins',
    categoria: 'Ferramentas e Máquinas',
    setorId: 'sec-eng',
    setorNome: 'Engenharia & Manutenção',
    localizacao: 'Subsolo - Casa de Força e Geradores',
    responsavel: 'Eng. Paulo Vieira',
    anoAquisicao: 2021,
    valorOriginal: 118000.00,
    valorAtual: 88500.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: []
  },

  // Diretoria (Helena Martins)
  {
    id: 'pat-10001',
    numeroPatrimonio: 'PAT-10001',
    descricao: 'Painel de Vídeo Wall LED 4K 110 Polegadas para Telepresença',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-dir',
    setorNome: 'Diretoria Executiva',
    localizacao: 'Bloco Executivo - Cobertura - Sala do Conselho',
    responsavel: 'Dra. Helena Martins',
    anoAquisicao: 2024,
    valorOriginal: 65000.00,
    valorAtual: 58500.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: []
  }
];

export const INITIAL_CAUTELAS = [
  {
    id: 'caut-501',
    assetId: 'pat-1004',
    numeroPatrimonio: 'PAT-1004',
    descricao: 'Projetor Epson PowerLite W49 3800 Lumens WXGA',
    responsavelRetirada: 'Lucas Rocha (Marketing)',
    documento: 'MG-14.882.102',
    telefone: '(11) 98765-4321',
    setorOrigem: 'Tecnologia da Informação (TI)',
    setorDestino: 'Marketing & Comunicação',
    dataRetirada: '2026-09-28 09:00',
    dataPrevistaDevolucao: '2026-10-02 18:00',
    finalidade: 'Apresentação do Plano Anual de Comunicação na Sala Multiuso',
    status: 'EM_ANDAMENTO',
    observacoes: 'Entregue com cabo HDMI de 5m, controle remoto e bolsa de transporte.',
    dataDevolucao: null,
    condicaoDevolucao: null
  }
];
