export const INITIAL_ASSETS = [
  // ================= FOYER (Alex) =================
  {
    id: 'pat-42542',
    numeroPatrimonio: '42542',
    quantidade: 4,
    descricao: '4 Monitores 40 polegadas profissionais',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-foyer',
    setorNome: 'Foyer',
    localizacao: 'Foyer de Entrada - Painel Principal',
    responsavel: 'Alex',
    dataAquisicao: '12/04/2023',
    anoAquisicao: 2023,
    valorOriginal: 7200.00,
    valorAtual: 5760.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '12/04/2023 10:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42543',
    numeroPatrimonio: '42543',
    quantidade: 1,
    descricao: '1 Sistema de áudio (2 subwoofers e 4 caixas acústicas)',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-foyer',
    setorNome: 'Foyer',
    localizacao: 'Foyer de Entrada - Sistema de Som Embutido',
    responsavel: 'Alex',
    dataAquisicao: '15/06/2023',
    anoAquisicao: 2023,
    valorOriginal: 4800.00,
    valorAtual: 3840.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/06/2023 11:20', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42544',
    numeroPatrimonio: '42544',
    quantidade: 2,
    descricao: '2 Mesas de apoio para colocar copos',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-foyer',
    setorNome: 'Foyer',
    localizacao: 'Foyer de Entrada - Lateral',
    responsavel: 'Alex',
    dataAquisicao: '10/05/2023',
    anoAquisicao: 2023,
    valorOriginal: 900.00,
    valorAtual: 720.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/05/2023 09:15', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },

  // ================= RECEPÇÃO (Alex) =================
  {
    id: 'pat-42545',
    numeroPatrimonio: '42545',
    quantidade: 1,
    descricao: 'Mesa de recepção e atendimento para 2 pessoas',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-recepcao',
    setorNome: 'Recepção',
    localizacao: 'Recepção Térreo - Balcão Principal',
    responsavel: 'Alex',
    dataAquisicao: '20/02/2023',
    anoAquisicao: 2023,
    valorOriginal: 1800.00,
    valorAtual: 1440.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '20/02/2023 08:30', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42546',
    numeroPatrimonio: '42546',
    quantidade: 1,
    descricao: '1 Computador Desktop Core i5 16GB 512GB SSD',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-recepcao',
    setorNome: 'Recepção',
    localizacao: 'Recepção Térreo - Mesa de Atendimento',
    responsavel: 'Alex',
    dataAquisicao: '15/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 3800.00,
    valorAtual: 2850.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/03/2023 10:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42547',
    numeroPatrimonio: '42547',
    quantidade: 1,
    descricao: '1 Monitor LED 24 polegadas Full HD',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-recepcao',
    setorNome: 'Recepção',
    localizacao: 'Recepção Térreo - Mesa de Atendimento',
    responsavel: 'Alex',
    dataAquisicao: '15/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 850.00,
    valorAtual: 680.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/03/2023 10:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42548',
    numeroPatrimonio: '42548',
    quantidade: 1,
    descricao: '1 Aparelho telefônico corporativo IP',
    categoria: 'Equipamentos de Comunicação',
    setorId: 'sec-recepcao',
    setorNome: 'Recepção',
    localizacao: 'Recepção Térreo - Ramal 100',
    responsavel: 'Alex',
    dataAquisicao: '10/01/2023',
    anoAquisicao: 2023,
    valorOriginal: 350.00,
    valorAtual: 260.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/01/2023 09:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },

  // ================= LABORATÓRIO INOVAÇÃO (Ricardo Mello) =================
  {
    id: 'pat-42549',
    numeroPatrimonio: '42549',
    quantidade: 2,
    descricao: '2 Mesas de trabalho colaborativo modular',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-lab-inovacao',
    setorNome: 'Laboratório Inovação',
    localizacao: 'Lab Inovação - Sala Central',
    responsavel: 'Ricardo Mello',
    dataAquisicao: '18/07/2023',
    anoAquisicao: 2023,
    valorOriginal: 2400.00,
    valorAtual: 1920.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '18/07/2023 14:00', acao: 'Cadastro Inicial', usuario: 'Ricardo Mello' }]
  },
  {
    id: 'pat-42550',
    numeroPatrimonio: '42550',
    quantidade: 1,
    descricao: '1 Sofá de recepção / descompressão 3 lugares',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-lab-inovacao',
    setorNome: 'Laboratório Inovação',
    localizacao: 'Lab Inovação - Área de Ideação',
    responsavel: 'Ricardo Mello',
    dataAquisicao: '22/07/2023',
    anoAquisicao: 2023,
    valorOriginal: 2800.00,
    valorAtual: 2240.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '22/07/2023 15:30', acao: 'Cadastro Inicial', usuario: 'Ricardo Mello' }]
  },
  {
    id: 'pat-42551',
    numeroPatrimonio: '42551',
    quantidade: 1,
    descricao: '1 TV Interativa Touch Screen 75 polegadas 4K',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-lab-inovacao',
    setorNome: 'Laboratório Inovação',
    localizacao: 'Lab Inovação - Parede Interativa',
    responsavel: 'Ricardo Mello',
    dataAquisicao: '10/09/2023',
    anoAquisicao: 2023,
    valorOriginal: 14500.00,
    valorAtual: 11600.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/09/2023 11:00', acao: 'Cadastro Inicial', usuario: 'Ricardo Mello' }]
  },
  {
    id: 'pat-42552',
    numeroPatrimonio: '42552',
    quantidade: 1,
    descricao: 'Mesa de reunião redonda com 4 cadeiras estofadas',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-lab-inovacao',
    setorNome: 'Laboratório Inovação',
    localizacao: 'Lab Inovação - Espaço Brainstorm',
    responsavel: 'Ricardo Mello',
    dataAquisicao: '05/08/2023',
    anoAquisicao: 2023,
    valorOriginal: 3400.00,
    valorAtual: 2720.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '05/08/2023 16:00', acao: 'Cadastro Inicial', usuario: 'Ricardo Mello' }]
  },

  // ================= REVISTA JMU (Alexandre) =================
  {
    id: 'pat-42553',
    numeroPatrimonio: '42553',
    quantidade: 1,
    descricao: '1 Ilha de trabalho operacional (composta por 4 mesas)',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-revista-jmu',
    setorNome: 'Revista JMU',
    localizacao: 'Redação Revista JMU - Núcleo Central',
    responsavel: 'Alexandre',
    dataAquisicao: '14/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 4800.00,
    valorAtual: 3840.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '14/03/2023 09:00', acao: 'Cadastro Inicial', usuario: 'Alexandre' }]
  },
  {
    id: 'pat-42554',
    numeroPatrimonio: '42554',
    quantidade: 4,
    descricao: '4 Computadores Desktop de alta performance para diagramação',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-revista-jmu',
    setorNome: 'Revista JMU',
    localizacao: 'Redação Revista JMU - Ilha 01',
    responsavel: 'Alexandre',
    dataAquisicao: '20/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 18000.00,
    valorAtual: 13500.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '20/03/2023 11:30', acao: 'Cadastro Inicial', usuario: 'Alexandre' }]
  },
  {
    id: 'pat-42555',
    numeroPatrimonio: '42555',
    quantidade: 8,
    descricao: '8 Monitores 27 polegadas Full HD (2 por pessoa / posto)',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-revista-jmu',
    setorNome: 'Revista JMU',
    localizacao: 'Redação Revista JMU - Ilha 01 (Display Duplo)',
    responsavel: 'Alexandre',
    dataAquisicao: '20/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 8800.00,
    valorAtual: 6600.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '20/03/2023 11:30', acao: 'Cadastro Inicial', usuario: 'Alexandre' }]
  },
  {
    id: 'pat-42556',
    numeroPatrimonio: '42556',
    quantidade: 4,
    descricao: '4 Cadeiras giratórias ergonômicas com apoio de braço',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-revista-jmu',
    setorNome: 'Revista JMU',
    localizacao: 'Redação Revista JMU - Postos de Trabalho',
    responsavel: 'Alexandre',
    dataAquisicao: '14/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 3120.00,
    valorAtual: 2496.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1580481077195-c3a821a58875?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '14/03/2023 09:30', acao: 'Cadastro Inicial', usuario: 'Alexandre' }]
  },
  {
    id: 'pat-42557',
    numeroPatrimonio: '42557',
    quantidade: 1,
    descricao: '1 Aparelho telefônico corporativo IP',
    categoria: 'Equipamentos de Comunicação',
    setorId: 'sec-revista-jmu',
    setorNome: 'Revista JMU',
    localizacao: 'Redação Revista JMU - Ramal 204',
    responsavel: 'Alexandre',
    dataAquisicao: '10/01/2023',
    anoAquisicao: 2023,
    valorOriginal: 350.00,
    valorAtual: 260.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/01/2023 10:00', acao: 'Cadastro Inicial', usuario: 'Alexandre' }]
  },

  // ================= SACADI E CADMI (Alex e Siqueira (substituto)) =================
  {
    id: 'pat-42558',
    numeroPatrimonio: '42558',
    quantidade: 8,
    descricao: '8 Ilhas de trabalho completas (4 mesas cada, com divisórias e mesinhas de apoio)',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-sacadi-cadmi',
    setorNome: 'SACADI E CADMI',
    localizacao: 'Salão Principal - Ilhas 01 a 08',
    responsavel: 'Alex e Siqueira (substituto)',
    dataAquisicao: '10/02/2023',
    anoAquisicao: 2023,
    valorOriginal: 33600.00,
    valorAtual: 26880.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/02/2023 08:00', acao: 'Cadastro Inicial', usuario: 'Alex e Siqueira' }]
  },
  {
    id: 'pat-42559',
    numeroPatrimonio: '42559',
    quantidade: 32,
    descricao: '32 Gaveteiros volantes metálicos com chave',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-sacadi-cadmi',
    setorNome: 'SACADI E CADMI',
    localizacao: 'Salão Principal - Sob as Mesas das Ilhas',
    responsavel: 'Alex e Siqueira (substituto)',
    dataAquisicao: '10/02/2023',
    anoAquisicao: 2023,
    valorOriginal: 14400.00,
    valorAtual: 11520.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/02/2023 08:30', acao: 'Cadastro Inicial', usuario: 'Alex e Siqueira' }]
  },
  {
    id: 'pat-42560',
    numeroPatrimonio: '42560',
    quantidade: 32,
    descricao: '32 Computadores Desktop Corporativo Core i5',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-sacadi-cadmi',
    setorNome: 'SACADI E CADMI',
    localizacao: 'Salão Principal - 32 Postos de Atendimento',
    responsavel: 'Alex e Siqueira (substituto)',
    dataAquisicao: '01/04/2023',
    anoAquisicao: 2023,
    valorOriginal: 124800.00,
    valorAtual: 93600.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '01/04/2023 09:00', acao: 'Cadastro Inicial', usuario: 'Alex e Siqueira' }]
  },
  {
    id: 'pat-42561',
    numeroPatrimonio: '42561',
    quantidade: 64,
    descricao: '64 Monitores LED 24 polegadas (sempre 2 por pessoa)',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-sacadi-cadmi',
    setorNome: 'SACADI E CADMI',
    localizacao: 'Salão Principal - Displays Duplos nos 32 Postos',
    responsavel: 'Alex e Siqueira (substituto)',
    dataAquisicao: '01/04/2023',
    anoAquisicao: 2023,
    valorOriginal: 54400.00,
    valorAtual: 40800.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '01/04/2023 09:30', acao: 'Cadastro Inicial', usuario: 'Alex e Siqueira' }]
  },
  {
    id: 'pat-42562',
    numeroPatrimonio: '42562',
    quantidade: 32,
    descricao: '32 Cadeiras giratórias ergonômicas NR-17',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-sacadi-cadmi',
    setorNome: 'SACADI E CADMI',
    localizacao: 'Salão Principal - Ilhas 01 a 08',
    responsavel: 'Alex e Siqueira (substituto)',
    dataAquisicao: '10/02/2023',
    anoAquisicao: 2023,
    valorOriginal: 24000.00,
    valorAtual: 19200.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1580481077195-c3a821a58875?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/02/2023 10:00', acao: 'Cadastro Inicial', usuario: 'Alex e Siqueira' }]
  },
  {
    id: 'pat-42563',
    numeroPatrimonio: '42563',
    quantidade: 8,
    descricao: '8 Aparelhos telefônicos IP (1 por Ilha de atendimento)',
    categoria: 'Equipamentos de Comunicação',
    setorId: 'sec-sacadi-cadmi',
    setorNome: 'SACADI E CADMI',
    localizacao: 'Salão Principal - Ramais das Ilhas',
    responsavel: 'Alex e Siqueira (substituto)',
    dataAquisicao: '15/01/2023',
    anoAquisicao: 2023,
    valorOriginal: 2800.00,
    valorAtual: 2100.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/01/2023 11:00', acao: 'Cadastro Inicial', usuario: 'Alex e Siqueira' }]
  },

  // ================= TI (Santana) =================
  {
    id: 'pat-42564',
    numeroPatrimonio: '42564',
    quantidade: 1,
    descricao: 'Contêiner Modular Data Center com Racks de Servidores',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-ti',
    setorNome: 'TI',
    localizacao: 'Área Técnica TI - Contêiner Servidores',
    responsavel: 'Santana',
    dataAquisicao: '15/11/2022',
    anoAquisicao: 2022,
    valorOriginal: 180000.00,
    valorAtual: 144000.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/11/2022 10:00', acao: 'Cadastro Inicial', usuario: 'Santana' }]
  },
  {
    id: 'pat-42565',
    numeroPatrimonio: '42565',
    quantidade: 10,
    descricao: 'Todos os computadores da equipe de TI',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-ti',
    setorNome: 'TI',
    localizacao: 'Sala Suporte TI - Bancadas',
    responsavel: 'Santana',
    dataAquisicao: '10/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 42000.00,
    valorAtual: 31500.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/03/2023 10:00', acao: 'Cadastro Inicial', usuario: 'Santana' }]
  },
  {
    id: 'pat-42566',
    numeroPatrimonio: '42566',
    quantidade: 20,
    descricao: 'Monitores de suporte e monitoramento da TI',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-ti',
    setorNome: 'TI',
    localizacao: 'Sala Suporte TI - Parede NOC e Bancadas',
    responsavel: 'Santana',
    dataAquisicao: '10/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 19000.00,
    valorAtual: 14250.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/03/2023 10:30', acao: 'Cadastro Inicial', usuario: 'Santana' }]
  },
  {
    id: 'pat-42567',
    numeroPatrimonio: '42567',
    quantidade: 1,
    descricao: '1 Impressora Multifuncional Laser Corporativa de Rede',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-ti',
    setorNome: 'TI',
    localizacao: 'Sala TI - Estação de Impressão',
    responsavel: 'Santana',
    dataAquisicao: '05/05/2023',
    anoAquisicao: 2023,
    valorOriginal: 3800.00,
    valorAtual: 2850.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '05/05/2023 14:00', acao: 'Cadastro Inicial', usuario: 'Santana' }]
  },
  {
    id: 'pat-42568',
    numeroPatrimonio: '42568',
    quantidade: 4,
    descricao: '4 Notebooks Dell Latitude Core i7 16GB 512GB SSD',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-ti',
    setorNome: 'TI',
    localizacao: 'Armário Cofre TI - Carga Portátil',
    responsavel: 'Santana',
    dataAquisicao: '20/06/2023',
    anoAquisicao: 2023,
    valorOriginal: 24800.00,
    valorAtual: 19840.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '20/06/2023 15:00', acao: 'Cadastro Inicial', usuario: 'Santana' }]
  },
  {
    id: 'pat-42569',
    numeroPatrimonio: '42569',
    quantidade: 2,
    descricao: '2 Notebooks HP ProBook Core i5 16GB SSD',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-ti',
    setorNome: 'TI',
    localizacao: 'Armário Cofre TI - Carga Portátil',
    responsavel: 'Santana',
    dataAquisicao: '12/08/2023',
    anoAquisicao: 2023,
    valorOriginal: 10800.00,
    valorAtual: 8640.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '12/08/2023 16:00', acao: 'Cadastro Inicial', usuario: 'Santana' }]
  },
  {
    id: 'pat-42570',
    numeroPatrimonio: '42570',
    quantidade: 3,
    descricao: '3 Notebooks Daten Corporativo Core i5',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-ti',
    setorNome: 'TI',
    localizacao: 'Armário Cofre TI - Carga Portátil',
    responsavel: 'Santana',
    dataAquisicao: '18/09/2023',
    anoAquisicao: 2023,
    valorOriginal: 12900.00,
    valorAtual: 10320.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '18/09/2023 10:45', acao: 'Cadastro Inicial', usuario: 'Santana' }]
  },
  {
    id: 'pat-42571',
    numeroPatrimonio: '42571',
    quantidade: 2,
    descricao: '2 Ultrabooks Premium ultrafinos Core i7',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-ti',
    setorNome: 'TI',
    localizacao: 'Armário Cofre TI - Reserva Executiva',
    responsavel: 'Santana',
    dataAquisicao: '05/10/2023',
    anoAquisicao: 2023,
    valorOriginal: 17800.00,
    valorAtual: 14240.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '05/10/2023 14:30', acao: 'Cadastro Inicial', usuario: 'Santana' }]
  },
  {
    id: 'pat-42572',
    numeroPatrimonio: '42572',
    quantidade: 2,
    descricao: '2 Tablets corporativos 10.5 polegadas com capa protetora',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-ti',
    setorNome: 'TI',
    localizacao: 'Armário Cofre TI',
    responsavel: 'Santana',
    dataAquisicao: '15/07/2023',
    anoAquisicao: 2023,
    valorOriginal: 4800.00,
    valorAtual: 3840.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/07/2023 11:00', acao: 'Cadastro Inicial', usuario: 'Santana' }]
  },
  {
    id: 'pat-42573',
    numeroPatrimonio: '42573',
    quantidade: 2,
    descricao: '2 HDs Externos 1 TB USB 3.0 para backup',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-ti',
    setorNome: 'TI',
    localizacao: 'Gaveta Segurança TI',
    responsavel: 'Santana',
    dataAquisicao: '10/02/2023',
    anoAquisicao: 2023,
    valorOriginal: 760.00,
    valorAtual: 570.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/02/2023 09:30', acao: 'Cadastro Inicial', usuario: 'Santana' }]
  },

  // ================= SALA DE REUNIÕES (Alex / Santana) =================
  // Carga do ALEX na Sala de Reuniões:
  {
    id: 'pat-42574',
    numeroPatrimonio: '42574',
    quantidade: 22,
    descricao: '22 Cadeiras executivas estofadas para sala de reuniões (CARGA ALEX)',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-reunioes',
    setorNome: 'Sala de Reuniões',
    localizacao: 'Sala de Reuniões Principal - Em torno da mesa',
    responsavel: 'Alex',
    dataAquisicao: '14/04/2023',
    anoAquisicao: 2023,
    valorOriginal: 14960.00,
    valorAtual: 11968.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1580481077195-c3a821a58875?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '14/04/2023 10:00', acao: 'Cadastro Inicial (Carga Alex)', usuario: 'Alex' }]
  },
  {
    id: 'pat-42575',
    numeroPatrimonio: '42575',
    quantidade: 1,
    descricao: '1 Mesa de reuniões executiva em formato de ferradura (CARGA ALEX)',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-reunioes',
    setorNome: 'Sala de Reuniões',
    localizacao: 'Sala de Reuniões Principal - Centro',
    responsavel: 'Alex',
    dataAquisicao: '14/04/2023',
    anoAquisicao: 2023,
    valorOriginal: 8500.00,
    valorAtual: 6800.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '14/04/2023 10:30', acao: 'Cadastro Inicial (Carga Alex)', usuario: 'Alex' }]
  },
  // Carga do SANTANA na Sala de Reuniões:
  {
    id: 'pat-42576',
    numeroPatrimonio: '42576',
    quantidade: 1,
    descricao: '1 Computador de conferência da Sala de Reuniões (CARGA SANTANA)',
    categoria: 'Equipamentos de Informática',
    setorId: 'sec-reunioes',
    setorNome: 'Sala de Reuniões',
    localizacao: 'Sala de Reuniões Principal - Rack AV',
    responsavel: 'Santana',
    dataAquisicao: '20/04/2023',
    anoAquisicao: 2023,
    valorOriginal: 3900.00,
    valorAtual: 2925.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '20/04/2023 14:00', acao: 'Cadastro Inicial (Carga Santana)', usuario: 'Santana' }]
  },
  {
    id: 'pat-42577',
    numeroPatrimonio: '42577',
    quantidade: 1,
    descricao: '1 Projetor Multimídia Laser Full HD de teto (CARGA SANTANA)',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-reunioes',
    setorNome: 'Sala de Reuniões',
    localizacao: 'Sala de Reuniões Principal - Fixação no Teto',
    responsavel: 'Santana',
    dataAquisicao: '20/04/2023',
    anoAquisicao: 2023,
    valorOriginal: 6800.00,
    valorAtual: 5100.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '20/04/2023 14:30', acao: 'Cadastro Inicial (Carga Santana)', usuario: 'Santana' }]
  },
  {
    id: 'pat-42578',
    numeroPatrimonio: '42578',
    quantidade: 1,
    descricao: '1 Tela de projeção retrátil elétrica motorizada 120 pol. (CARGA SANTANA)',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-reunioes',
    setorNome: 'Sala de Reuniões',
    localizacao: 'Sala de Reuniões Principal - Parede Frontal',
    responsavel: 'Santana',
    dataAquisicao: '20/04/2023',
    anoAquisicao: 2023,
    valorOriginal: 2200.00,
    valorAtual: 1650.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '20/04/2023 15:00', acao: 'Cadastro Inicial (Carga Santana)', usuario: 'Santana' }]
  },
  {
    id: 'pat-42579',
    numeroPatrimonio: '42579',
    quantidade: 1,
    descricao: '1 Sistema de áudio e cancelamento de eco BIAMP (CARGA SANTANA)',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-reunioes',
    setorNome: 'Sala de Reuniões',
    localizacao: 'Sala de Reuniões Principal - Rack de Áudio',
    responsavel: 'Santana',
    dataAquisicao: '25/05/2023',
    anoAquisicao: 2023,
    valorOriginal: 16500.00,
    valorAtual: 13200.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '25/05/2023 11:00', acao: 'Cadastro Inicial (Carga Santana)', usuario: 'Santana' }]
  },
  {
    id: 'pat-42580',
    numeroPatrimonio: '42580',
    quantidade: 1,
    descricao: '1 Caixa de som acústica ativa (CARGA SANTANA)',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-reunioes',
    setorNome: 'Sala de Reuniões',
    localizacao: 'Sala de Reuniões Principal - Suporte de Parede',
    responsavel: 'Santana',
    dataAquisicao: '25/05/2023',
    anoAquisicao: 2023,
    valorOriginal: 2900.00,
    valorAtual: 2320.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '25/05/2023 11:30', acao: 'Cadastro Inicial (Carga Santana)', usuario: 'Santana' }]
  },
  {
    id: 'pat-42581',
    numeroPatrimonio: '42581',
    quantidade: 1,
    descricao: '1 TV 75 polegadas 4K para videoconferência (CARGA SANTANA)',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-reunioes',
    setorNome: 'Sala de Reuniões',
    localizacao: 'Sala de Reuniões Principal - Painel Lateral',
    responsavel: 'Santana',
    dataAquisicao: '10/06/2023',
    anoAquisicao: 2023,
    valorOriginal: 6200.00,
    valorAtual: 4960.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/06/2023 16:00', acao: 'Cadastro Inicial (Carga Santana)', usuario: 'Santana' }]
  },

  // ================= COPA COZINHA TÉRREO (Alex) =================
  {
    id: 'pat-42582',
    numeroPatrimonio: '42582',
    quantidade: 1,
    descricao: 'Freezer horizontal 300L 1 porta',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-copa-terreo',
    setorNome: 'Copa Cozinha Térreo',
    localizacao: 'Cozinha Térreo',
    responsavel: 'Alex',
    dataAquisicao: '10/01/2023',
    anoAquisicao: 2023,
    valorOriginal: 2400.00,
    valorAtual: 1920.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/01/2023 09:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42583',
    numeroPatrimonio: '42583',
    quantidade: 1,
    descricao: 'Geladeira duplex Frost Free inox',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-copa-terreo',
    setorNome: 'Copa Cozinha Térreo',
    localizacao: 'Cozinha Térreo',
    responsavel: 'Alex',
    dataAquisicao: '10/01/2023',
    anoAquisicao: 2023,
    valorOriginal: 3600.00,
    valorAtual: 2880.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/01/2023 09:30', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42584',
    numeroPatrimonio: '42584',
    quantidade: 1,
    descricao: 'Fogão industrial 4 bocas com forno',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-copa-terreo',
    setorNome: 'Copa Cozinha Térreo',
    localizacao: 'Cozinha Térreo',
    responsavel: 'Alex',
    dataAquisicao: '10/01/2023',
    anoAquisicao: 2023,
    valorOriginal: 1850.00,
    valorAtual: 1480.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/01/2023 10:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42585',
    numeroPatrimonio: '42585',
    quantidade: 1,
    descricao: 'Forno Micro-ondas 34 litros inox',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-copa-terreo',
    setorNome: 'Copa Cozinha Térreo',
    localizacao: 'Cozinha Térreo - Bancada',
    responsavel: 'Alex',
    dataAquisicao: '15/02/2023',
    anoAquisicao: 2023,
    valorOriginal: 750.00,
    valorAtual: 600.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/02/2023 11:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42586',
    numeroPatrimonio: '42586',
    quantidade: 1,
    descricao: 'Forno elétrico de bancada 44L inox',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-copa-terreo',
    setorNome: 'Copa Cozinha Térreo',
    localizacao: 'Cozinha Térreo - Bancada',
    responsavel: 'Alex',
    dataAquisicao: '15/02/2023',
    anoAquisicao: 2023,
    valorOriginal: 680.00,
    valorAtual: 544.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/02/2023 11:30', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42587',
    numeroPatrimonio: '42587',
    quantidade: 1,
    descricao: 'Mesa de refeitório com 4 cadeiras fixas',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-copa-terreo',
    setorNome: 'Copa Cozinha Térreo',
    localizacao: 'Cozinha Térreo - Centro',
    responsavel: 'Alex',
    dataAquisicao: '10/01/2023',
    anoAquisicao: 2023,
    valorOriginal: 1200.00,
    valorAtual: 960.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/01/2023 14:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },

  // ================= COPA 1º PISO (Alex) =================
  {
    id: 'pat-42588',
    numeroPatrimonio: '42588',
    quantidade: 1,
    descricao: 'Fogão de bancada 4 bocas automático',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-copa-1piso',
    setorNome: 'Copa 1º Piso',
    localizacao: 'Copa 1º Andar - Bancada Central',
    responsavel: 'Alex',
    dataAquisicao: '12/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 950.00,
    valorAtual: 760.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '12/03/2023 10:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42589',
    numeroPatrimonio: '42589',
    quantidade: 1,
    descricao: 'Geladeira Frost Free 375L inox',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-copa-1piso',
    setorNome: 'Copa 1º Piso',
    localizacao: 'Copa 1º Andar - Canto',
    responsavel: 'Alex',
    dataAquisicao: '12/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 3200.00,
    valorAtual: 2560.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '12/03/2023 10:30', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42590',
    numeroPatrimonio: '42590',
    quantidade: 1,
    descricao: 'Liquidificador industrial de alta rotação',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-copa-1piso',
    setorNome: 'Copa 1º Piso',
    localizacao: 'Copa 1º Andar - Bancada',
    responsavel: 'Alex',
    dataAquisicao: '12/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 380.00,
    valorAtual: 304.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '12/03/2023 11:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42591',
    numeroPatrimonio: '42591',
    quantidade: 1,
    descricao: 'Purificador / Filtro de água elétrico refrigerado',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-copa-1piso',
    setorNome: 'Copa 1º Piso',
    localizacao: 'Copa 1º Andar - Parede Bancada',
    responsavel: 'Alex',
    dataAquisicao: '12/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 890.00,
    valorAtual: 712.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '12/03/2023 11:30', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42592',
    numeroPatrimonio: '42592',
    quantidade: 1,
    descricao: 'Cafeteira elétrica industrial inox',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-copa-1piso',
    setorNome: 'Copa 1º Piso',
    localizacao: 'Copa 1º Andar - Bancada Café',
    responsavel: 'Alex',
    dataAquisicao: '12/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 520.00,
    valorAtual: 416.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1517668808822-9ebb02ae2a0e?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '12/03/2023 12:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42593',
    numeroPatrimonio: '42593',
    quantidade: 1,
    descricao: 'TV Smart LED 65 polegadas 4K',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-copa-1piso',
    setorNome: 'Copa 1º Piso',
    localizacao: 'Copa 1º Andar - Parede Refeitório',
    responsavel: 'Alex',
    dataAquisicao: '20/05/2023',
    anoAquisicao: 2023,
    valorOriginal: 3900.00,
    valorAtual: 3120.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '20/05/2023 15:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42594',
    numeroPatrimonio: '42594',
    quantidade: 1,
    descricao: 'Mesa ampla para refeitório',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-copa-1piso',
    setorNome: 'Copa 1º Piso',
    localizacao: 'Copa 1º Andar - Centro',
    responsavel: 'Alex',
    dataAquisicao: '15/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 1600.00,
    valorAtual: 1280.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/03/2023 13:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42595',
    numeroPatrimonio: '42595',
    quantidade: 8,
    descricao: '8 Cadeiras estofadas para refeitório',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-copa-1piso',
    setorNome: 'Copa 1º Piso',
    localizacao: 'Copa 1º Andar - Em torno da Mesa',
    responsavel: 'Alex',
    dataAquisicao: '15/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 1760.00,
    valorAtual: 1408.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1580481077195-c3a821a58875?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/03/2023 13:30', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42596',
    numeroPatrimonio: '42596',
    quantidade: 5,
    descricao: '5 Banquetas altas cromadas para bancada',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-copa-1piso',
    setorNome: 'Copa 1º Piso',
    localizacao: 'Copa 1º Andar - Bancada Alta',
    responsavel: 'Alex',
    dataAquisicao: '15/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 950.00,
    valorAtual: 760.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1503602642458-232111445657?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/03/2023 14:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42597',
    numeroPatrimonio: '42597',
    quantidade: 1,
    descricao: 'Batedeira planetária inox',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-copa-1piso',
    setorNome: 'Copa 1º Piso',
    localizacao: 'Copa 1º Andar - Armário Copa',
    responsavel: 'Alex',
    dataAquisicao: '12/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 450.00,
    valorAtual: 360.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '12/03/2023 14:30', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42598',
    numeroPatrimonio: '42598',
    quantidade: 1,
    descricao: 'Forno micro-ondas 32L digital',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-copa-1piso',
    setorNome: 'Copa 1º Piso',
    localizacao: 'Copa 1º Andar - Bancada',
    responsavel: 'Alex',
    dataAquisicao: '12/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 720.00,
    valorAtual: 576.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '12/03/2023 15:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42599',
    numeroPatrimonio: '42599',
    quantidade: 1,
    descricao: 'Forno elétrico de bancada 45L',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-copa-1piso',
    setorNome: 'Copa 1º Piso',
    localizacao: 'Copa 1º Andar - Bancada',
    responsavel: 'Alex',
    dataAquisicao: '12/03/2023',
    anoAquisicao: 2023,
    valorOriginal: 680.00,
    valorAtual: 544.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '12/03/2023 15:30', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },
  {
    id: 'pat-42600',
    numeroPatrimonio: '42600',
    quantidade: 1,
    descricao: '1 Aparelho telefônico ramal copa',
    categoria: 'Equipamentos de Comunicação',
    setorId: 'sec-copa-1piso',
    setorNome: 'Copa 1º Piso',
    localizacao: 'Copa 1º Andar - Ramal 115',
    responsavel: 'Alex',
    dataAquisicao: '10/01/2023',
    anoAquisicao: 2023,
    valorOriginal: 280.00,
    valorAtual: 210.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '10/01/2023 16:00', acao: 'Cadastro Inicial', usuario: 'Alex' }]
  },

  // ================= STUDIO (Tadeu) =================
  {
    id: 'pat-42601',
    numeroPatrimonio: '42601',
    quantidade: 2,
    descricao: '2 Câmeras broadcast 4K com kit de iluminação LED de estúdio',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-studio',
    setorNome: 'Studio',
    localizacao: 'Studio de Gravação - Grid de Iluminação e Pedestais',
    responsavel: 'Tadeu',
    dataAquisicao: '08/04/2023',
    anoAquisicao: 2023,
    valorOriginal: 25600.00,
    valorAtual: 20480.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '08/04/2023 10:00', acao: 'Cadastro Inicial', usuario: 'Tadeu' }]
  },
  {
    id: 'pat-42602',
    numeroPatrimonio: '42602',
    quantidade: 1,
    descricao: 'Mesa controladora de corte e switcher de transmissão de vídeo',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-studio',
    setorNome: 'Studio',
    localizacao: 'Studio de Gravação - Mesa Técnica de Produção',
    responsavel: 'Tadeu',
    dataAquisicao: '08/04/2023',
    anoAquisicao: 2023,
    valorOriginal: 7900.00,
    valorAtual: 6320.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '08/04/2023 10:30', acao: 'Cadastro Inicial', usuario: 'Tadeu' }]
  },
  {
    id: 'pat-42603',
    numeroPatrimonio: '42603',
    quantidade: 4,
    descricao: '4 Microfones sem fio de lapela profissionais e pedestais',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-studio',
    setorNome: 'Studio',
    localizacao: 'Studio de Gravação - Maleta Técnica',
    responsavel: 'Tadeu',
    dataAquisicao: '08/04/2023',
    anoAquisicao: 2023,
    valorOriginal: 5800.00,
    valorAtual: 4640.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '08/04/2023 11:00', acao: 'Cadastro Inicial', usuario: 'Tadeu' }]
  },

  // ================= AUDITÓRIO (Tadeu) =================
  {
    id: 'pat-42604',
    numeroPatrimonio: '42604',
    quantidade: 1,
    descricao: 'Mesa de som digital e sistema de PA acústico do auditório',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-auditorio',
    setorNome: 'Auditório',
    localizacao: 'Auditório Principal - Cabine de Som',
    responsavel: 'Tadeu',
    dataAquisicao: '15/02/2023',
    anoAquisicao: 2023,
    valorOriginal: 22000.00,
    valorAtual: 17600.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/02/2023 09:00', acao: 'Cadastro Inicial', usuario: 'Tadeu' }]
  },
  {
    id: 'pat-42605',
    numeroPatrimonio: '42605',
    quantidade: 1,
    descricao: 'Projetor Laser de alta potência 7000 Lumens WUXGA',
    categoria: 'Aparelhos Eletroeletrônicos',
    setorId: 'sec-auditorio',
    setorNome: 'Auditório',
    localizacao: 'Auditório Principal - Teto Central',
    responsavel: 'Tadeu',
    dataAquisicao: '15/02/2023',
    anoAquisicao: 2023,
    valorOriginal: 18500.00,
    valorAtual: 14800.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/02/2023 09:30', acao: 'Cadastro Inicial', usuario: 'Tadeu' }]
  },
  {
    id: 'pat-42606',
    numeroPatrimonio: '42606',
    quantidade: 80,
    descricao: '80 Poltronas rebatíveis estofadas com prancheta retrátil',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-auditorio',
    setorNome: 'Auditório',
    localizacao: 'Auditório Principal - Fileiras A a H',
    responsavel: 'Tadeu',
    dataAquisicao: '15/02/2023',
    anoAquisicao: 2023,
    valorOriginal: 33600.00,
    valorAtual: 26880.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/02/2023 10:00', acao: 'Cadastro Inicial', usuario: 'Tadeu' }]
  },
  {
    id: 'pat-42607',
    numeroPatrimonio: '42607',
    quantidade: 1,
    descricao: 'Púlpito em acrílico com microfone gooseneck integrado',
    categoria: 'Mobiliário em Geral',
    setorId: 'sec-auditorio',
    setorNome: 'Auditório',
    localizacao: 'Auditório Principal - Palco',
    responsavel: 'Tadeu',
    dataAquisicao: '15/02/2023',
    anoAquisicao: 2023,
    valorOriginal: 2600.00,
    valorAtual: 2080.00,
    status: 'ATIVO',
    baixado: false,
    foto: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=500&auto=format&fit=crop&q=60',
    conferidoEm: null,
    conferidoPor: null,
    cautelaAtual: null,
    historico: [{ data: '15/02/2023 10:30', acao: 'Cadastro Inicial', usuario: 'Tadeu' }]
  }
];

export const INITIAL_CAUTELAS = [
  {
    id: 'caut-501',
    assetId: 'pat-42568',
    numeroPatrimonio: '42568',
    descricao: 'Notebook Dell Latitude Core i7 16GB 512GB SSD',
    responsavelRetirada: 'Alexandre',
    documento: 'MG-14.882.102',
    telefone: '(61) 98765-4321',
    setorOrigem: 'TI',
    setorDestino: 'Revista JMU',
    dataRetirada: '28/09/2026 09:00',
    dataPrevistaDevolucao: '05/10/2026 18:00',
    finalidade: 'Cobertura externa e edição de reportagem especial da Revista JMU',
    observacoes: 'Acompanha fonte carregadora Dell e mouse sem fio',
    status: 'EM_ANDAMENTO'
  }
];
